# RMT CONFIGURATION FILE
# RASTER Music Tracker 1.35

# GENERAL

SCALEPERCENTAGE = 100
TRACKLINEPRIMARYHIGHLIGHT = 8
TRACKLINESECONDARYHIGHLIGHT = 4
TRACKLINEALTNUMBERING = 0
DISPLAYFLATNOTES = 0
USEGERMANNOTATION = 0
NTSC_SYSTEM = 0
NOHWSOUNDBUFFER = 0
TRACKERDRIVERVERSION = 6

# KEYBOARD

KEYBOARD_LAYOUT = 0
KEYBOARD_UPDOWNCONTINUE = 1
KEYBOARD_REMEMBEROCTAVESANDVOLUMES = 1
KEYBOARD_ESCRESETATARISOUND = 1
KEYBOARD_ASKWHENCONTROL_S = 1

# MIDI

MIDI_IN = 
MIDI_TR = 0
MIDI_VOLUMEOFFSET = 0
MIDI_NOTEOFF = 0

# PATHS

PATH_DEFAULTSONGS = 
PATH_DEFAULTINSTRUMENTS = 
PATH_DEFAULTTRACKS = 
PATH_LASTSONGS = C:\Users\JAC\Desktop\ASMA-Input\Test
PATH_LASTINSTRUMENTS = 
PATH_LASTTRACKS = 

# VIEW

VIEW_MAINTOOLBAR = 1
VIEW_BLOCKTOOLBAR = 1
VIEW_STATUSBAR = 1
VIEW_PLAYTIMECOUNTER = 1
VIEW_VOLUMEANALYZER = 1
VIEW_POKEYCHIPREGISTERS = 1
VIEW_INSTRUMENTACTIVEHELP = 1
SMOOTH_SCROLL = 1
VIEW_DEBUGDISPLAY = 1
