# RMT CONFIGURATION FILE
# RASTER Music Tracker 1.35

# TUNING

TUNING = 440.83751645933
BASENOTE = 3
TEMPERAMENT = 0

# RATIOS

UNISON = 1 / 1
MIN_2ND = 20 / 19
MAJ_2ND = 10 / 9
MIN_3RD = 20 / 17
MAJ_3RD = 5 / 4
PERF_4TH = 4 / 3
TRITONE = 60 / 43
PERF_5TH = 3 / 2
MIN_6TH = 30 / 19
MAJ_6TH = 5 / 3
MIN_7TH = 30 / 17
MAJ_7TH = 15 / 8
OCTAVE = 2 / 1
